defaults: &defaults
  host: <%= ENV["RAILS_REDIS_ADDRESS"].split(":", 2).first %>
  port: <%= ENV["RAILS_REDIS_ADDRESS"].split(":", 2).last %>
  password: <%= GlobalSetting.redis_password %>
  db: <%= GlobalSetting.redis_db %>

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
